### ISSUE TITLE
Add Test case for: import type * as types from ‘./file;  export {types}; 

### ISSUE THREAD

**Issue by kendallgassner** [intuit/eslint-plugin-no-explicit-type-exports#11]
This test case should Pass

```
import type * as types from "./table";
export {types};
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnAVHAhgZwclPAMyghDgCIA6AegA8KBuAKBTsljgBMUisBXADbwA3klQ4Avi2ZA

**Comment by Rashmi-K-A** [comment]
Hey @kendallgassner, would like to pick this one! Could you assign this to me please?
