### ISSUE TITLE
This should pass but fails: import { justAType } from ‘./file’; export type {justAType};

### ISSUE THREAD

**Issue by kendallgassner** [intuit/eslint-plugin-no-explicit-type-exports#13]
```
import { justAType } from ‘./file’; 
export type {justAType};
```

This should pass but fails.

If you do not export the imported type then the import will be removed when compiled down to js and will not cause bugs.

**Comment by DianaTdr** [comment]
Hi @kendallgassner, I've raised an issue for this here: https://github.com/intuit/eslint-plugin-no-explicit-type-exports/pull/40 Please have a look when you got some time :)
