### ISSUE TITLE
add auto's all contributors plugin

### ISSUE THREAD

**Issue by kendallgassner** [intuit/eslint-plugin-no-explicit-type-exports#16]
Auto: https://github.com/intuit/auto
Plugin: https://github.com/intuit/auto/tree/master/plugins/all-contributors

**Comment by rajatdiptabiswas** [comment]
Hi @kendallgassner 

I'd like to work on this. 
Would you kindly let me know what exactly needs to be done?
I'll try to get it fixed as soon as possible.

**Comment by kendallgassner** [comment]
Hi @rajatdiptabiswas!

I already use auto in the jenkins pipeline to build/release this project. What I would like is to add the all contributors plugin to be able to add contributors to the readme as people merge code into this project.

Plugin: https://github.com/intuit/auto/tree/master/plugins/all-contributors

This readme ^ can guide you through the process of adding the plugin

**Comment by rajatdiptabiswas** [comment]
Hi @kendallgassner 

I am not exactly sure if I managed to make all the required changes.

Kindly take a look and let me know if you need something changed.
I'll try to get them fixed.

I used the following settings to set up `npx all-contributors init`.
<img width="913" alt="Screen Shot 2020-10-01 at 2 09 54 AM" src="https://user-images.githubusercontent.com/32998741/94735111-09d21600-038c-11eb-81b3-02e6e5dbfe1f.png">

Thanks!
