### ISSUE TITLE
Ability to auto-fix exported types

### ISSUE THREAD

**Issue by adierkens** [intuit/eslint-plugin-no-explicit-type-exports#4]
I'd like for the `--fix` flag to remove the offending type export

**Comment by kendallgassner** [comment]
I like this idea. Although, I worry this could break someone's project. Should removing an export from a file be something that the code owner controls? An explicit type export would break if it was installed and transpiled in a javascript repo but It would not break if it was installed in a typescript repo.

**Comment by kendallgassner** [comment]
Added Fix: [v0.11.0](https://github.com/intuit/eslint-plugin-no-explicit-type-exports/releases/tag/v0.11.0)
